Repository gdvl777/school_library_OOP, pull requests merged in 2023-11, with the labels that each got.

#1 Add classes and initial config
  .github/workflows/linters.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  MIT.md
  README.md
  person.rb
  student.rb
  teacher.rb
Labels: documentation, enhancement

#5 Code Refactoring
  Gemfile
  Gemfile.lock
  README.md
  app.rb
  app_interface.rb
  main.rb
  modules/create_entities.rb
  modules/list_entities.rb
  modules/user_interface.rb
  person.rb
  student.rb
  teacher.rb
Labels: documentation, enhancement, refactor

#6 Preserve Data on JSON
  .rubocop.yml
  Gemfile.lock
  README.md
  app.rb
  book.rb
  classroom.rb
  db/books.json
  db/people.json
  db/rentals.json
  modules/books_data_manipulation.rb
  modules/people_data_manipulation.rb
  modules/rentals_data_manipulation.rb
  person.rb
  rental.rb
  student.rb
  teacher.rb
Labels: documentation, enhancement

#7 Unit Testing
  .github/workflows/tests.yml
  .rspec
  Gemfile
  Gemfile.lock
  README.md
  classroom.rb
  spec/book_spec.rb
  spec/classroom_spec.rb
  spec/decorators_spec.rb
  spec/person_spec.rb
  spec/rental_spec.rb
  spec/spec_helper.rb
  spec/student_spec.rb
  spec/teacher_spec.rb
  student.rb
  teacher.rb
Labels: documentation, enhancement, refactor, dependencies
